In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/enjoysport/ENJOYSPORT.csv

In [2]:
data = pd.read_csv('/kaggle/input/enjoysport/ENJOYSPORT.csv', encoding='latin')
data

     Sky AirTemp Humidity    Wind Water Forecast  EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same           1
1  Sunny    Warm     High  Strong  Warm     Same           1
2  Rainy    Cold     High  Strong  Warm   Change           0
3  Sunny    Warm     High  Strong  Cool   Change           1

In [3]:
d = np.array(data)[:,:-1]
print("\n The attributes are: ",d)
target = np.array(data)[:,-1]
print("\n The target is: ",target)

 The attributes are:  [['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
 ['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same']
 ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change']
 ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change']]

 The target is:  [1 1 0 1]

In [4]:
def findS(c,t):
    for i, val in enumerate(t):
        if val == 1:
            specific_hypothesis = c[i].copy()
            break
             
    for i, val in enumerate(c):
        if t[i] == 1:
            for x in range(len(specific_hypothesis)):
                if val[x] != specific_hypothesis[x]:
                    specific_hypothesis[x] = '?'
                else:
                    pass
                 
    return specific_hypothesis

In [5]:
print("\n The final hypothesis is:",findS(d,target))

 The final hypothesis is: ['Sunny' 'Warm' '?' 'Strong' '?' '?']

In [9]:
second_data = pd.read_csv('/kaggle/input/purchase/purchase.csv', encoding='latin')
second_data

  citations    size inLibrary       price editions  buy
0      some   small        no  affordable     many    0
1      many     big        no   expensive      one    1
2      some     big    always   expensive      few    0
3      many  medium        no   expensive     many    1
4      many   small        no  affordable     many    1

In [10]:
ds = np.array(second_data)[:,:-1]
print("\n The attributes are: ",ds)
targets = np.array(second_data)[:,-1]
print("\n The target is: ",targets)

 The attributes are:  [['some' 'small' 'no' 'affordable' 'many']
 ['many' 'big' 'no' 'expensive' 'one']
 ['some' 'big' 'always' 'expensive' 'few']
 ['many' 'medium' 'no' 'expensive' 'many']
 ['many' 'small' 'no' 'affordable' 'many']]

 The target is:  [0 1 0 1 1]

In [11]:
print("\n The final hypothesis is:",findS(ds,targets))

 The final hypothesis is: ['many' '?' 'no' '?' '?']